### ISSUE TITLE
Staking/onboarding

### ISSUE THREAD

**Issue by adamkdean** [edge/cli#19]
The next step will be to rewrite the Edge CLI to be more intuitive and wallet based. The previous version of CLI used Console user accounts, but the new version will work with XE wallets exclusively. The initial version of the CLI should support the creation & management of stakes, as well as functionality for initialising new devices. Initialisation of new devices will consist of generating an XE wallet for the device, assigning the device wallet address to a stake, before pulling the current version of `edge/host` and running it (with access to the device wallet).

- [x] https://github.com/edge/cli/issues/3
- [x] https://github.com/edge/cli/issues/4
- [x] https://github.com/edge/cli/issues/5
- [x] https://github.com/edge/cli/issues/6
- [x] https://github.com/edge/cli/issues/7
- [x] https://github.com/edge/cli/issues/8
- [x] https://github.com/edge/cli/issues/9
- [x] https://github.com/edge/cli/issues/10
- [x] https://github.com/edge/cli/issues/11
- [x] https://github.com/edge/cli/issues/12
- [x] https://github.com/edge/cli/issues/13
- [x] https://github.com/edge/cli/issues/14
- [x] https://github.com/edge/cli/issues/15
- [x] https://github.com/edge/cli/issues/16
- [x] https://github.com/edge/cli/issues/17
- [x] https://github.com/edge/cli/issues/18
- [x] https://github.com/edge/cli/issues/20
- [x] https://github.com/edge/cli/issues/21

Going forward, it will also be necessary to support CLI updates. This could be native, downloading the latest CLI binary. We should also move to using `edge` as the application name, along with simplifying command line arguments, i.e.

```
edge device register
edge device start
edge stake create
edge stake ls
edge stake release [--express] <id>
edge stake unlock <id>
```

CLI will need to be able to create and manage all three stake types: stargate, gateway, and host.

**Comment by annybs** [comment]
With the closure of #16 and #18 I am informally expanding the scope of this issue to include UX discussion/planning. Specifics of this (so far) are available in Discord.

Over the next couple of days I will be focusing on developing a unified codebase for working with Docker that provides more consistent error handling and a more comprehensive API for service management. For instance, there shouldn't be any console.logging in device/data.ts.

After I've firmed up the groundwork, I will do as much as I can to make the UX consumer friendly by EOD Wednesday so we can trial onboarding in testnet.

**Comment by annybs** [comment]
Quick note, as discussed on Discord we're going to make digests a bit more, well, digestible:

- Truncated display length: 8 characters (can be displayed in full with `--full` or `--json` options, as appropriate)
- Input length: minimum 3 characters

So for example, the full digest `73cf787ac831b33f1f32d0380ce75b5c32f6d738ff3e5a51e0a7b09979466bf6`:

- Displays as `73cf787a` (1 in 4.2B chance of conflict with another digest)
- Can be input as `73c` (1 in 4K chance, still pretty low)

This should make them easier to read and write, and in the event of an input not resolving to an unique digest, additional specificity can be added one character at a time - NBD.

**Comment by adamkdean** [comment]
If there is a conflict with another digest, we just show a message like git does, asking them to be more specific

**Comment by annybs** [comment]
As mentioned in the onboarding draft, there are some outstanding UX issues right now. Quick run down off the top of my head:

- The aforementioned digest truncation
- Standardising some inconsistent language, e.g. `service` -> `${stake.type}` or `node` (depending on context)
- Stake selection when adding a device so the digest doesn't have to be pasted in

I also think that some loss of speed in the `device` commands (because of the need to access Docker volume for device info) counts as a UX issue, but I think this is probably OS-specific as a result of disk virtualization on OSX/Windows, and we don't anticipate device commands being heavily used, so I'm not losing sleep over it right now. Just want to make a note of that for my own future reference.

**Comment by adamkdean** [comment]
FYI, loss of speed on commands is fine as long as we provide feedback to the user

**Comment by annybs** [comment]
Nearly done with basic formatting updates. I'll start pasting example output for each command here to demonstrate and gather any feedback.

**edge device add**

Standard interactive add:

```
% ./bin/edgetest device add   

> @edge/cli@1.0.4 testnet:dev
> ts-node src/main-testnet.ts "device" "add"

Initializing device...

Select a stake to assign this device to:

1. 4bfd03ff (Stargate)
2. c5487704 (Gateway)
3. d7291f9b (Host)
4. d0fdfd38 (Host)
5. 1c888f97 (Host)
6. 6e13f80a (Host)

Enter a number: (1-6) 6

You are adding this device to Edge Testnet.

This device will be assigned to stake 6e13f80a, allowing this device to operate a Host node.

Add this device? [yn] y

This transaction must be signed with your private key.
Please enter your passphrase to decrypt your private key, sign your transaction, and submit it to the blockchain.

Passphrase: 

Your transaction has been submitted and will appear in the explorer shortly.

https://test.network/transaction/01ab345118f278e457ddc7d362c0cd6b7504891fe044040be5faa167486eb56c

You may run 'edgetest tx lsp' to check progress of your pending transaction. When your stake transaction has been processed it will no longer be listed as pending.

You can then run 'edgetest device start' to start a Host node on this device.
```

Already staked:

```
% ./bin/edgetest device add      
This device is already assigned to stake 7b9181af (Host) on Edge Testnet.

To reassign this device, run 'edgetest device remove' first to remove it from the network, then run 'edgetest device add' again to add it back.
```

> I'm wondering if the change of stake here would be confusing for users who aren't aware the stake hash is recalculated after every mutation. Perhaps we should consider displaying stake IDs instead/in addition? Maybe something for a future update, not MVP.

Partial output with `-D, --full-digests`:

```
% ./bin/edgetest device add -D
Initializing device...

Select a stake to assign this device to:

1. 4bfd03ff9c829507110a0201904d5fd860ed60842850be64b1cb7fc8c7493764 (Stargate)
2. c5487704bde7416cf481d5bec3f28734278f20a6e1dbe26d03e2d0df34bd31b0 (Gateway)
3. d7291f9bf14722947856e5bb67e5b2b1677567baca7c9f3169f6aaf21af9d03a (Host)
4. d0fdfd38ce2dfdfc6863a35efed25bbb095b37481d675d148f1ca686145981dc (Host)
5. 1c888f97fda26ecc23a2a8e3961b336964bdddaf06f14c49e1e46c2c56a8f3e4 (Host)
6. 7b9181afaddf8c1f6abb63ecfdb1085c75b9fc08ecad14c925b8dc07d4fc406c (Host)

Enter a number: (1-6) InputError: cancelled
```

Partial match argument:

```
% ./bin/edgetest device add 1c8
You are adding this device to Edge Testnet.

This device will be assigned to stake 1c888f97, allowing this device to operate a Host node.

Add this device? [yn] InputError: cancelled
```

Partial match error:

```
% ./bin/edgetest device add 1c 
Error: input hash must be at least 3 characters
```

**Comment by annybs** [comment]
**edge device info**

Initialized but unassigned: (uncommon state, can be reached by starting to `add` a device but dropping out partway)

```
% ./bin/edgetest device info
Network:   Testnet
Device ID: xe_dB2D84c2723b0AFFe3D689227d12AF855f5921c9
Stake:     Unassigned
```

Assigned:

```
% ./bin/edgetest device info
Network:   Testnet
Device ID: xe_dB2D84c2723b0AFFe3D689227d12AF855f5921c9
Type:      Host
Stake:     1b77f126
```

Assigned, showing full digests:

```
% ./bin/edgetest device info -D
Network:   Testnet
Device ID: xe_dB2D84c2723b0AFFe3D689227d12AF855f5921c9
Type:      Host
Stake:     1b77f1267efa3071ff2fa0576ccaad3a2a515ef3bd6df4a5b41c2f21210f5d5f
```

Not initialized:

```
% ./bin/edgetest device info  
Error: device has not been initialized
```

**Comment by annybs** [comment]
Device controls, pasted together because their output is much more minimal than the above:

```
% ./bin/edgetest device start
Host started
% ./bin/edgetest device status
Host is running
% ./bin/edgetest device restart
Host restarted
% ./bin/edgetest device stop
Host stopped
% ./bin/edgetest device status
Host is not running
```

The same again on an uninitialized device:

```
% ./bin/edgetest device start
Error: device has not been initialized
% ./bin/edgetest device status
Error: device has not been initialized
% ./bin/edgetest device restart
Error: device has not been initialized
% ./bin/edgetest device stop
Error: device has not been initialized
```

**Comment by adamkdean** [comment]
> I'm wondering if the change of stake here would be confusing for users who aren't aware the stake hash is recalculated after every mutation. Perhaps we should consider displaying stake IDs instead/in addition? Maybe something for a future update, not MVP.

Maybe show `ID (Hash)`?

**Comment by annybs** [comment]
**edge device remove**

I'll just do one example, because this command doesn't take any arguments and I anecdotally confirm that `--full-digests` works here too:

```
% ./bin/edgetest device remove
You are removing this device from Edge Testnet.

This will remove this device's assignment to stake 1b77f126 (Host).

Remove this device? [yn] y

This transaction must be signed with your private key.
Please enter your passphrase to decrypt your private key, sign your transaction, and submit it to the blockchain.

Passphrase:

Unassigning stake...

Your transaction has been submitted and will appear in the explorer shortly.

https://test.network/transaction/cb446942cbdda009fad4b23f95a252616899a72a7920e7ab6a123301f077164b

Stopping Host...

Removing device...

This device has been removed from Edge Testnet.
```

**Comment by annybs** [comment]
Please post any further feedback on the onboarding PR #43 rather than here. This issue to be closed after onboarding goes to testnet.
