### ISSUE TITLE
Allow stake reassign in device add

### ISSUE THREAD

**Issue by annybs** [edge/cli#60]
@adamkdean 
> technically, you can assign a device _over_ a stake with a device already assigned
> in which case it replaces it

Presently, assigned stakes cannot be reassigned through CLI. This should be changed to allow stake reassignment. If the existing device is running, network behaviours will remove it automatically without further requirements of CLI. See also https://github.com/edge/stargate/issues/6

**Comment by adamkdean** [comment]
When listing stakes to assign a new device to, we be sure to should show the status of the stakes, e.g. `unassigned` `assigned to host xe_12592368...`
