### ISSUE TITLE
File access issues when running as non-root user

### ISSUE THREAD

**Issue by adamkdean** [edge/cli#89]
```
$ edge device remove
[critical] Error: EACCES: permission denied, open '/var/lib/docker/volumes/edge-device-data/_data/address' {}
```

**Comment by annybs** [comment]
Potentially related to #61

**Comment by adamkdean** [comment]
I think is due to the CLI process accessing root files, likely just needs sudo

**Comment by annybs** [comment]
Per https://github.com/edge/cli/issues/61
> This is mitigated by changes in v1.7.2 #116 which use container-oriented volume management instead of interacting directly with the disk. This makes it simpler to configure sudoless Docker access without encountering file access issues.
> 
> The original behaviour of direct volume read/write can be reinstated by setting `DOCKER_DIRECT_RW=true` in the environment. The volume access issues obtain if not accessing Docker as root, but may be preferable for some users (particularly as it doesn't require pulling `alpine` to facilitate data transfers).

I am proceeding to close this issue as a duplicate.
